export default {
	CREATE_TABLE_CATEGORIES: "CREATE TABLE IF NOT EXISTS categories (id INTEGER PRIMARY KEY, title TEXT, _id TEXT)",
	CREATE_TABLE_LAST_TIME_IN: "CREATE TABLE IF NOT EXISTS lastTIME (id INTEGER PRIMARY KEY, lastimein TEXT)",

	SAVE_COLUMNS_CATEGORIES: "INSERT INTO categories (title, _id) VALUES (?, ?)",
	SAVE_COLUMNS_LAST_TIME_IN: "INSERT INTO lastTIME (lastimein) VALUES (?)",

	GET_COLUMNS_CATEGORIES: "SELECT * FROM categories",
	GET_COLUMNS_LAST_TIME_IN: "SELECT * FROM lastTIME",

	UPDATE_COLUMN_CATEGORIES: "UPDATE categories SET title = ? WHERE _id = ?",
};
